### ISSUE TITLE
syntax error at or near ,

### ISSUE THREAD

**Issue by stoamandl** [lukeattard/fail2report#1]
Hello to down under,
nice shell script!! 

I have problems getting it to work.
Installation works, but after that every action seems to run on the same error.
Here is the output for fail2report load.
`Updating database from /var/log/fail2ban.log.  Please wait 
awk: /usr/lib/fail2report/UnbanIP.awk: line 12: syntax error at or near ,
awk: /usr/lib/fail2report/UnbanIP.awk: line 13: syntax error at or near ,
awk: /usr/lib/fail2report/BanIP.awk: line 11: syntax error at or near ,
awk: /usr/lib/fail2report/BanIP.awk: line 12: syntax error at or near ,
awk: /usr/lib/fail2report/FoundIP.awk: line 15: syntax error at or near ,
awk: /usr/lib/fail2report/FoundIP.awk: line 16: syntax error at or near ,
`
Have I missed something or done something wrong?

Best regards
Jan

**Comment by lukeattard** [comment]
I have not been able to replicate the issue, I will need more info on your setup, what distro etc?
